version: 2
jobs:
  build_and_test:
    macos:
      xcode: 13.1.0
    steps:
      - checkout
      - run:
          name: Xcode version
          command: xcode-select -p
      - run:
          name: List simulators
          command: xcrun simctl list
      - run:
          name: Install dependencies
          command: |
            gem install xcpretty cocoapods jazzy
      - run:
          name: Test
          command: make test-pretty
      - run:
          name: Docs
          command: make docs
      - run:
          name: Lint
          command: make lint
      - run:
          name: Build example
          command: make build-example-pretty
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
