# When a new release is created on GitHub, this workflow sends an event
# to cross-platform SDK repos that depend on native iOS SDK
name: Notify
on:
  # Triggered when a new release is tagged in GitHub.
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  notify:
    runs-on: macos-latest
    steps:
      - name:
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: radarlabs/react-native-radar
          event-type: ios-sdk-release
          client-payload: '{"release": "${{ github.event.release.tag_name }}"}'
