# This is a basic workflow to help you get started with Actions

name: Radar SDK iOS Release

# Controls when the workflow will run
on:
  # Triggered when a new release is tagged in GitHub.
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, test, and analyze
        run: xcodebuild -workspace RadarSDK.xcodeproj/project.xcworkspace -scheme XCFramework -destination "platform=iOS Simulator,name=iPhone 11" clean build analyze test | xcpretty
